name: build and publish website
on:
  push:
    branches:
      - main

jobs:
  build_and_publish_website:
    name: build and publish website
    runs-on: ubuntu-latest
    steps:
      - name: setup emsdk
        uses: mymindstorm/setup-emsdk@v9
        with:
          version: 2.0.3
      - name: build
        run: ls
        working-directory: ./web
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web/build